-- Remove legacy numbered demo tags when they are not used anymore.
DELETE FROM tags
WHERE slug LIKE 'demo-tag-%'
  AND name LIKE 'Demo Tag %'
  AND NOT EXISTS (
    SELECT 1
    FROM image_tags
    WHERE image_tags.tag_id = tags.id
  );

-- Reuse existing readable tags when they already exist in the catalog.
INSERT IGNORE INTO tags (name, slug, is_active, deleted_at)
VALUES
  ('Nature', 'nature', 1, NULL),
  ('Travel', 'travel', 1, NULL),
  ('Food', 'food', 1, NULL),
  ('City', 'city', 1, NULL),
  ('Portrait', 'portrait', 1, NULL),
  ('Animals', 'animals', 1, NULL),
  ('Architecture', 'architecture', 1, NULL),
  ('Beach', 'beach', 1, NULL),
  ('Mountains', 'mountains', 1, NULL),
  ('Street', 'street', 1, NULL),
  ('Night', 'night', 1, NULL),
  ('Minimal', 'minimal', 1, NULL),
  ('Vintage', 'vintage', 1, NULL),
  ('Fashion', 'fashion', 1, NULL),
  ('Sports', 'sports', 1, NULL),
  ('Technology', 'technology', 1, NULL),
  ('Art', 'art', 1, NULL),
  ('Music', 'music', 1, NULL),
  ('Flowers', 'flowers', 1, NULL),
  ('Abstract', 'abstract', 1, NULL);

INSERT INTO images (image_url, thumbnail_url, width, height, alt_text, source, is_active, deleted_at)
VALUES
  ('https://placehold.co/1200x900?text=Demo+Image+001', 'https://placehold.co/400x300?text=Thumb+001', 1200, 900, 'Demo Image 001', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+002', 'https://placehold.co/400x300?text=Thumb+002', 900, 1200, 'Demo Image 002', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+003', 'https://placehold.co/400x300?text=Thumb+003', 1080, 1080, 'Demo Image 003', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+004', 'https://placehold.co/400x300?text=Thumb+004', 1600, 900, 'Demo Image 004', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+005', 'https://placehold.co/400x300?text=Thumb+005', 1000, 1400, 'Demo Image 005', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+006', 'https://placehold.co/400x300?text=Thumb+006', 1200, 900, 'Demo Image 006', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+007', 'https://placehold.co/400x300?text=Thumb+007', 900, 1200, 'Demo Image 007', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+008', 'https://placehold.co/400x300?text=Thumb+008', 1080, 1080, 'Demo Image 008', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+009', 'https://placehold.co/400x300?text=Thumb+009', 1600, 900, 'Demo Image 009', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+010', 'https://placehold.co/400x300?text=Thumb+010', 1000, 1400, 'Demo Image 010', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+011', 'https://placehold.co/400x300?text=Thumb+011', 1200, 900, 'Demo Image 011', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+012', 'https://placehold.co/400x300?text=Thumb+012', 900, 1200, 'Demo Image 012', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+013', 'https://placehold.co/400x300?text=Thumb+013', 1080, 1080, 'Demo Image 013', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+014', 'https://placehold.co/400x300?text=Thumb+014', 1600, 900, 'Demo Image 014', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+015', 'https://placehold.co/400x300?text=Thumb+015', 1000, 1400, 'Demo Image 015', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+016', 'https://placehold.co/400x300?text=Thumb+016', 1200, 900, 'Demo Image 016', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+017', 'https://placehold.co/400x300?text=Thumb+017', 900, 1200, 'Demo Image 017', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+018', 'https://placehold.co/400x300?text=Thumb+018', 1080, 1080, 'Demo Image 018', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+019', 'https://placehold.co/400x300?text=Thumb+019', 1600, 900, 'Demo Image 019', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+020', 'https://placehold.co/400x300?text=Thumb+020', 1000, 1400, 'Demo Image 020', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+021', 'https://placehold.co/400x300?text=Thumb+021', 1200, 900, 'Demo Image 021', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+022', 'https://placehold.co/400x300?text=Thumb+022', 900, 1200, 'Demo Image 022', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+023', 'https://placehold.co/400x300?text=Thumb+023', 1080, 1080, 'Demo Image 023', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+024', 'https://placehold.co/400x300?text=Thumb+024', 1600, 900, 'Demo Image 024', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+025', 'https://placehold.co/400x300?text=Thumb+025', 1000, 1400, 'Demo Image 025', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+026', 'https://placehold.co/400x300?text=Thumb+026', 1200, 900, 'Demo Image 026', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+027', 'https://placehold.co/400x300?text=Thumb+027', 900, 1200, 'Demo Image 027', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+028', 'https://placehold.co/400x300?text=Thumb+028', 1080, 1080, 'Demo Image 028', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+029', 'https://placehold.co/400x300?text=Thumb+029', 1600, 900, 'Demo Image 029', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+030', 'https://placehold.co/400x300?text=Thumb+030', 1000, 1400, 'Demo Image 030', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+031', 'https://placehold.co/400x300?text=Thumb+031', 1200, 900, 'Demo Image 031', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+032', 'https://placehold.co/400x300?text=Thumb+032', 900, 1200, 'Demo Image 032', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+033', 'https://placehold.co/400x300?text=Thumb+033', 1080, 1080, 'Demo Image 033', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+034', 'https://placehold.co/400x300?text=Thumb+034', 1600, 900, 'Demo Image 034', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+035', 'https://placehold.co/400x300?text=Thumb+035', 1000, 1400, 'Demo Image 035', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+036', 'https://placehold.co/400x300?text=Thumb+036', 1200, 900, 'Demo Image 036', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+037', 'https://placehold.co/400x300?text=Thumb+037', 900, 1200, 'Demo Image 037', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+038', 'https://placehold.co/400x300?text=Thumb+038', 1080, 1080, 'Demo Image 038', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+039', 'https://placehold.co/400x300?text=Thumb+039', 1600, 900, 'Demo Image 039', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+040', 'https://placehold.co/400x300?text=Thumb+040', 1000, 1400, 'Demo Image 040', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+041', 'https://placehold.co/400x300?text=Thumb+041', 1200, 900, 'Demo Image 041', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+042', 'https://placehold.co/400x300?text=Thumb+042', 900, 1200, 'Demo Image 042', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+043', 'https://placehold.co/400x300?text=Thumb+043', 1080, 1080, 'Demo Image 043', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+044', 'https://placehold.co/400x300?text=Thumb+044', 1600, 900, 'Demo Image 044', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+045', 'https://placehold.co/400x300?text=Thumb+045', 1000, 1400, 'Demo Image 045', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+046', 'https://placehold.co/400x300?text=Thumb+046', 1200, 900, 'Demo Image 046', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+047', 'https://placehold.co/400x300?text=Thumb+047', 900, 1200, 'Demo Image 047', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+048', 'https://placehold.co/400x300?text=Thumb+048', 1080, 1080, 'Demo Image 048', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+049', 'https://placehold.co/400x300?text=Thumb+049', 1600, 900, 'Demo Image 049', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+050', 'https://placehold.co/400x300?text=Thumb+050', 1000, 1400, 'Demo Image 050', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+051', 'https://placehold.co/400x300?text=Thumb+051', 1200, 900, 'Demo Image 051', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+052', 'https://placehold.co/400x300?text=Thumb+052', 900, 1200, 'Demo Image 052', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+053', 'https://placehold.co/400x300?text=Thumb+053', 1080, 1080, 'Demo Image 053', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+054', 'https://placehold.co/400x300?text=Thumb+054', 1600, 900, 'Demo Image 054', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+055', 'https://placehold.co/400x300?text=Thumb+055', 1000, 1400, 'Demo Image 055', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+056', 'https://placehold.co/400x300?text=Thumb+056', 1200, 900, 'Demo Image 056', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+057', 'https://placehold.co/400x300?text=Thumb+057', 900, 1200, 'Demo Image 057', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+058', 'https://placehold.co/400x300?text=Thumb+058', 1080, 1080, 'Demo Image 058', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+059', 'https://placehold.co/400x300?text=Thumb+059', 1600, 900, 'Demo Image 059', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+060', 'https://placehold.co/400x300?text=Thumb+060', 1000, 1400, 'Demo Image 060', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+061', 'https://placehold.co/400x300?text=Thumb+061', 1200, 900, 'Demo Image 061', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+062', 'https://placehold.co/400x300?text=Thumb+062', 900, 1200, 'Demo Image 062', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+063', 'https://placehold.co/400x300?text=Thumb+063', 1080, 1080, 'Demo Image 063', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+064', 'https://placehold.co/400x300?text=Thumb+064', 1600, 900, 'Demo Image 064', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+065', 'https://placehold.co/400x300?text=Thumb+065', 1000, 1400, 'Demo Image 065', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+066', 'https://placehold.co/400x300?text=Thumb+066', 1200, 900, 'Demo Image 066', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+067', 'https://placehold.co/400x300?text=Thumb+067', 900, 1200, 'Demo Image 067', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+068', 'https://placehold.co/400x300?text=Thumb+068', 1080, 1080, 'Demo Image 068', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+069', 'https://placehold.co/400x300?text=Thumb+069', 1600, 900, 'Demo Image 069', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+070', 'https://placehold.co/400x300?text=Thumb+070', 1000, 1400, 'Demo Image 070', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+071', 'https://placehold.co/400x300?text=Thumb+071', 1200, 900, 'Demo Image 071', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+072', 'https://placehold.co/400x300?text=Thumb+072', 900, 1200, 'Demo Image 072', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+073', 'https://placehold.co/400x300?text=Thumb+073', 1080, 1080, 'Demo Image 073', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+074', 'https://placehold.co/400x300?text=Thumb+074', 1600, 900, 'Demo Image 074', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+075', 'https://placehold.co/400x300?text=Thumb+075', 1000, 1400, 'Demo Image 075', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+076', 'https://placehold.co/400x300?text=Thumb+076', 1200, 900, 'Demo Image 076', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+077', 'https://placehold.co/400x300?text=Thumb+077', 900, 1200, 'Demo Image 077', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+078', 'https://placehold.co/400x300?text=Thumb+078', 1080, 1080, 'Demo Image 078', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+079', 'https://placehold.co/400x300?text=Thumb+079', 1600, 900, 'Demo Image 079', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+080', 'https://placehold.co/400x300?text=Thumb+080', 1000, 1400, 'Demo Image 080', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+081', 'https://placehold.co/400x300?text=Thumb+081', 1200, 900, 'Demo Image 081', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+082', 'https://placehold.co/400x300?text=Thumb+082', 900, 1200, 'Demo Image 082', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+083', 'https://placehold.co/400x300?text=Thumb+083', 1080, 1080, 'Demo Image 083', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+084', 'https://placehold.co/400x300?text=Thumb+084', 1600, 900, 'Demo Image 084', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+085', 'https://placehold.co/400x300?text=Thumb+085', 1000, 1400, 'Demo Image 085', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+086', 'https://placehold.co/400x300?text=Thumb+086', 1200, 900, 'Demo Image 086', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+087', 'https://placehold.co/400x300?text=Thumb+087', 900, 1200, 'Demo Image 087', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+088', 'https://placehold.co/400x300?text=Thumb+088', 1080, 1080, 'Demo Image 088', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+089', 'https://placehold.co/400x300?text=Thumb+089', 1600, 900, 'Demo Image 089', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+090', 'https://placehold.co/400x300?text=Thumb+090', 1000, 1400, 'Demo Image 090', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+091', 'https://placehold.co/400x300?text=Thumb+091', 1200, 900, 'Demo Image 091', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+092', 'https://placehold.co/400x300?text=Thumb+092', 900, 1200, 'Demo Image 092', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+093', 'https://placehold.co/400x300?text=Thumb+093', 1080, 1080, 'Demo Image 093', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+094', 'https://placehold.co/400x300?text=Thumb+094', 1600, 900, 'Demo Image 094', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+095', 'https://placehold.co/400x300?text=Thumb+095', 1000, 1400, 'Demo Image 095', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1200x900?text=Demo+Image+096', 'https://placehold.co/400x300?text=Thumb+096', 1200, 900, 'Demo Image 096', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/900x1200?text=Demo+Image+097', 'https://placehold.co/400x300?text=Thumb+097', 900, 1200, 'Demo Image 097', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1080x1080?text=Demo+Image+098', 'https://placehold.co/400x300?text=Thumb+098', 1080, 1080, 'Demo Image 098', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1600x900?text=Demo+Image+099', 'https://placehold.co/400x300?text=Thumb+099', 1600, 900, 'Demo Image 099', 'seed:placehold.co', 1, NULL),
  ('https://placehold.co/1000x1400?text=Demo+Image+100', 'https://placehold.co/400x300?text=Thumb+100', 1000, 1400, 'Demo Image 100', 'seed:placehold.co', 1, NULL);

INSERT INTO image_tags (image_id, tag_id)
VALUES
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 001'), (SELECT id FROM tags WHERE slug = 'flowers')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 001'), (SELECT id FROM tags WHERE slug = 'street')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 001'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 001'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 002'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 002'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 003'), (SELECT id FROM tags WHERE slug = 'vintage')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 003'), (SELECT id FROM tags WHERE slug = 'city')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 003'), (SELECT id FROM tags WHERE slug = 'sports')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 003'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 003'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 004'), (SELECT id FROM tags WHERE slug = 'abstract')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 004'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 004'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 005'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 006'), (SELECT id FROM tags WHERE slug = 'fashion')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 006'), (SELECT id FROM tags WHERE slug = 'portrait')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 006'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 006'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 007'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 007'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 008'), (SELECT id FROM tags WHERE slug = 'beach')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 008'), (SELECT id FROM tags WHERE slug = 'flowers')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 008'), (SELECT id FROM tags WHERE slug = 'street')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 008'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 008'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 009'), (SELECT id FROM tags WHERE slug = 'sports')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 009'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 009'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 010'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 011'), (SELECT id FROM tags WHERE slug = 'mountains')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 011'), (SELECT id FROM tags WHERE slug = 'abstract')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 011'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 011'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 012'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 012'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 013'), (SELECT id FROM tags WHERE slug = 'food')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 013'), (SELECT id FROM tags WHERE slug = 'fashion')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 013'), (SELECT id FROM tags WHERE slug = 'portrait')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 013'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 013'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 014'), (SELECT id FROM tags WHERE slug = 'street')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 014'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 014'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 015'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 016'), (SELECT id FROM tags WHERE slug = 'city')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 016'), (SELECT id FROM tags WHERE slug = 'sports')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 016'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 016'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 017'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 017'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 018'), (SELECT id FROM tags WHERE slug = 'music')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 018'), (SELECT id FROM tags WHERE slug = 'mountains')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 018'), (SELECT id FROM tags WHERE slug = 'abstract')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 018'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 018'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 019'), (SELECT id FROM tags WHERE slug = 'portrait')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 019'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 019'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 020'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 021'), (SELECT id FROM tags WHERE slug = 'flowers')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 021'), (SELECT id FROM tags WHERE slug = 'street')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 021'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 021'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 022'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 022'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 023'), (SELECT id FROM tags WHERE slug = 'vintage')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 023'), (SELECT id FROM tags WHERE slug = 'city')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 023'), (SELECT id FROM tags WHERE slug = 'sports')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 023'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 023'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 024'), (SELECT id FROM tags WHERE slug = 'abstract')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 024'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 024'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 025'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 026'), (SELECT id FROM tags WHERE slug = 'fashion')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 026'), (SELECT id FROM tags WHERE slug = 'portrait')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 026'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 026'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 027'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 027'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 028'), (SELECT id FROM tags WHERE slug = 'beach')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 028'), (SELECT id FROM tags WHERE slug = 'flowers')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 028'), (SELECT id FROM tags WHERE slug = 'street')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 028'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 028'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 029'), (SELECT id FROM tags WHERE slug = 'sports')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 029'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 029'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 030'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 031'), (SELECT id FROM tags WHERE slug = 'mountains')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 031'), (SELECT id FROM tags WHERE slug = 'abstract')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 031'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 031'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 032'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 032'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 033'), (SELECT id FROM tags WHERE slug = 'food')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 033'), (SELECT id FROM tags WHERE slug = 'fashion')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 033'), (SELECT id FROM tags WHERE slug = 'portrait')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 033'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 033'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 034'), (SELECT id FROM tags WHERE slug = 'street')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 034'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 034'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 035'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 036'), (SELECT id FROM tags WHERE slug = 'city')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 036'), (SELECT id FROM tags WHERE slug = 'sports')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 036'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 036'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 037'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 037'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 038'), (SELECT id FROM tags WHERE slug = 'music')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 038'), (SELECT id FROM tags WHERE slug = 'mountains')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 038'), (SELECT id FROM tags WHERE slug = 'abstract')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 038'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 038'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 039'), (SELECT id FROM tags WHERE slug = 'portrait')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 039'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 039'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 040'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 041'), (SELECT id FROM tags WHERE slug = 'flowers')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 041'), (SELECT id FROM tags WHERE slug = 'street')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 041'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 041'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 042'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 042'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 043'), (SELECT id FROM tags WHERE slug = 'vintage')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 043'), (SELECT id FROM tags WHERE slug = 'city')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 043'), (SELECT id FROM tags WHERE slug = 'sports')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 043'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 043'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 044'), (SELECT id FROM tags WHERE slug = 'abstract')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 044'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 044'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 045'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 046'), (SELECT id FROM tags WHERE slug = 'fashion')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 046'), (SELECT id FROM tags WHERE slug = 'portrait')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 046'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 046'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 047'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 047'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 048'), (SELECT id FROM tags WHERE slug = 'beach')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 048'), (SELECT id FROM tags WHERE slug = 'flowers')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 048'), (SELECT id FROM tags WHERE slug = 'street')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 048'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 048'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 049'), (SELECT id FROM tags WHERE slug = 'sports')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 049'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 049'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 050'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 051'), (SELECT id FROM tags WHERE slug = 'mountains')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 051'), (SELECT id FROM tags WHERE slug = 'abstract')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 051'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 051'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 052'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 052'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 053'), (SELECT id FROM tags WHERE slug = 'food')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 053'), (SELECT id FROM tags WHERE slug = 'fashion')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 053'), (SELECT id FROM tags WHERE slug = 'portrait')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 053'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 053'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 054'), (SELECT id FROM tags WHERE slug = 'street')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 054'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 054'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 055'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 056'), (SELECT id FROM tags WHERE slug = 'city')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 056'), (SELECT id FROM tags WHERE slug = 'sports')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 056'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 056'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 057'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 057'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 058'), (SELECT id FROM tags WHERE slug = 'music')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 058'), (SELECT id FROM tags WHERE slug = 'mountains')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 058'), (SELECT id FROM tags WHERE slug = 'abstract')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 058'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 058'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 059'), (SELECT id FROM tags WHERE slug = 'portrait')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 059'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 059'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 060'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 061'), (SELECT id FROM tags WHERE slug = 'flowers')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 061'), (SELECT id FROM tags WHERE slug = 'street')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 061'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 061'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 062'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 062'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 063'), (SELECT id FROM tags WHERE slug = 'vintage')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 063'), (SELECT id FROM tags WHERE slug = 'city')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 063'), (SELECT id FROM tags WHERE slug = 'sports')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 063'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 063'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 064'), (SELECT id FROM tags WHERE slug = 'abstract')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 064'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 064'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 065'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 066'), (SELECT id FROM tags WHERE slug = 'fashion')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 066'), (SELECT id FROM tags WHERE slug = 'portrait')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 066'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 066'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 067'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 067'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 068'), (SELECT id FROM tags WHERE slug = 'beach')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 068'), (SELECT id FROM tags WHERE slug = 'flowers')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 068'), (SELECT id FROM tags WHERE slug = 'street')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 068'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 068'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 069'), (SELECT id FROM tags WHERE slug = 'sports')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 069'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 069'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 070'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 071'), (SELECT id FROM tags WHERE slug = 'mountains')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 071'), (SELECT id FROM tags WHERE slug = 'abstract')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 071'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 071'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 072'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 072'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 073'), (SELECT id FROM tags WHERE slug = 'food')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 073'), (SELECT id FROM tags WHERE slug = 'fashion')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 073'), (SELECT id FROM tags WHERE slug = 'portrait')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 073'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 073'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 074'), (SELECT id FROM tags WHERE slug = 'street')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 074'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 074'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 075'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 076'), (SELECT id FROM tags WHERE slug = 'city')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 076'), (SELECT id FROM tags WHERE slug = 'sports')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 076'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 076'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 077'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 077'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 078'), (SELECT id FROM tags WHERE slug = 'music')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 078'), (SELECT id FROM tags WHERE slug = 'mountains')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 078'), (SELECT id FROM tags WHERE slug = 'abstract')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 078'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 078'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 079'), (SELECT id FROM tags WHERE slug = 'portrait')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 079'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 079'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 080'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 081'), (SELECT id FROM tags WHERE slug = 'flowers')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 081'), (SELECT id FROM tags WHERE slug = 'street')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 081'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 081'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 082'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 082'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 083'), (SELECT id FROM tags WHERE slug = 'vintage')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 083'), (SELECT id FROM tags WHERE slug = 'city')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 083'), (SELECT id FROM tags WHERE slug = 'sports')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 083'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 083'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 084'), (SELECT id FROM tags WHERE slug = 'abstract')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 084'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 084'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 085'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 086'), (SELECT id FROM tags WHERE slug = 'fashion')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 086'), (SELECT id FROM tags WHERE slug = 'portrait')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 086'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 086'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 087'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 087'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 088'), (SELECT id FROM tags WHERE slug = 'beach')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 088'), (SELECT id FROM tags WHERE slug = 'flowers')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 088'), (SELECT id FROM tags WHERE slug = 'street')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 088'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 088'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 089'), (SELECT id FROM tags WHERE slug = 'sports')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 089'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 089'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 090'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 091'), (SELECT id FROM tags WHERE slug = 'mountains')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 091'), (SELECT id FROM tags WHERE slug = 'abstract')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 091'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 091'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 092'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 092'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 093'), (SELECT id FROM tags WHERE slug = 'food')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 093'), (SELECT id FROM tags WHERE slug = 'fashion')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 093'), (SELECT id FROM tags WHERE slug = 'portrait')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 093'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 093'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 094'), (SELECT id FROM tags WHERE slug = 'street')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 094'), (SELECT id FROM tags WHERE slug = 'nature')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 094'), (SELECT id FROM tags WHERE slug = 'minimal')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 095'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 096'), (SELECT id FROM tags WHERE slug = 'city')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 096'), (SELECT id FROM tags WHERE slug = 'sports')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 096'), (SELECT id FROM tags WHERE slug = 'animals')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 096'), (SELECT id FROM tags WHERE slug = 'art')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 097'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 097'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 098'), (SELECT id FROM tags WHERE slug = 'music')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 098'), (SELECT id FROM tags WHERE slug = 'mountains')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 098'), (SELECT id FROM tags WHERE slug = 'abstract')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 098'), (SELECT id FROM tags WHERE slug = 'night')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 098'), (SELECT id FROM tags WHERE slug = 'travel')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 099'), (SELECT id FROM tags WHERE slug = 'portrait')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 099'), (SELECT id FROM tags WHERE slug = 'technology')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 099'), (SELECT id FROM tags WHERE slug = 'architecture')),
  ((SELECT id FROM images WHERE source = 'seed:placehold.co' AND alt_text = 'Demo Image 100'), (SELECT id FROM tags WHERE slug = 'minimal'));
